artifacts_root: artifacts
data_annotation:
  data_save_dir: artifacts/data_ingestion/data
  frames_dir: artifacts/data_ingestion/video/frames
  image_size:
  - 640
  - 640
data_ingestion:
  frames_dir: artifacts/data_ingestion/video/frames
  from_video: false
  local_data_file: artifacts/data_ingestion/data.zip
  local_video_file: artifacts/data_ingestion/video/video.mp4
  lpd_path: models/lpd/license_plate_detector.pt
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/156EkmC1UCjVI4Eit4A_ItuJzXvuqMoyJ/view?usp=sharing
  unzip_dir: artifacts/data_ingestion
  video_dir: artifacts/data_ingestion/video
prepare_base_model:
  base_model_path: artifacts/prepare_base_model
  root_dir: artifacts/prepare_base_model
  source_URL: 9903d43bb5774c12a6a314e0b04bba14
  updated_base_model_path: yolov10m
training:
  format: onnx
  mlflow_uri: https://dagshub.com/mqasim41/license-plate-reader.mlflow
